#cloud-config
package_update: true
package_upgrade: true
packages:
  - curl
  - snapd
  - apt-transport-https
  - ca-certificates
  - software-properties-common
  - docker.io

runcmd:
  - snap install microk8s --classic
  - usermod -aG microk8s ubuntu
  - newgrp microk8s
  - microk8s status --wait-ready
  - microk8s enable dns storage ingress
  - usermod -aG docker ubuntu
  - systemctl enable --now docker
